### ISSUE TITLE
Know of an updated makefile for V8?

### ISSUE THREAD

**Issue by creationix** [bnoordhuis/v8.rs#2]
I ran across this while looking for a while to embed V8 in a Makefile based system.  You did a great job writing the makefile, but of course, it's out of date.

Do you know of any projects that have a more updated makefile for a newer v8 or have interest in helping me update this one?

The biggest change I've run across so far is a lot of inspector protocol stuff is now generated code in a whole sub project in the gn source.

**Comment by bnoordhuis** [comment]
Hi, Tim. I'm not aware of any projects. You could ask around on the v8-users@ mailing list.

**Comment by bnoordhuis** [comment]
You're not the only one interested in Makefile builds. From this morning: https://groups.google.com/d/msg/v8-users/HqxtY2NFeqc/iJmznmmMBgAJ

**Comment by creationix** [comment]
Thanks for the pointer.  I figured this would be the answer.
